### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected char 0xa0 at 37 in Mobile-Info value:

### ISSUE THREAD

**Issue by programmingCris** [Synerise/android-sdk#12]
Synerise SDK version: 5.9.0
Device: Android TV
Model -> Blaupunkt EU 2K Android TV
Android 11

Stack:
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0xa0 at 37 in Mobile-Info value: android;30;8751953;11;BLAUPUNKT EU 2K Android TV;Expressluck;5.9.0
       at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
       at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
       at okhttp3.Headers$Builder.set(Headers.kt:344)
       at okhttp3.Request$Builder.header(Request.kt:199)
       at com.synerise.sdk.a59.a(MobileInfoInterceptor.java:2)
       at com.synerise.sdk.a59.intercept(MobileInfoInterceptor.java:2)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.synerise.sdk.a29.intercept(HeaderInterceptor.java:2)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by konned** [comment]
It seems that in Build.MODEL there are spaces. It will be fixed in next release.

**Comment by programmingCris** [comment]
@konned Can you please share information about the next SDK release date?

**Comment by konned** [comment]
Next release will be in the first week of January.

**Comment by konned** [comment]
Fixed in 5.13.1
