### ISSUE TITLE
Crash on Synerise initialization - ExceptionInInitializerError(AppStartedEventManager.java:19)

### ISSUE THREAD

**Issue by tajchert** [Synerise/android-sdk#6]
Synerise SDK - 4.0.0
Android 6.0
Model: A503 Joy
Brand: Bravis

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.synerise.sdk.event.b.a(AppStartedEventManager.java:19)
       at com.synerise.sdk.event.Tracker.a(Tracker.java:2)
       at com.synerise.sdk.event.Tracker.init(Tracker.java:5)
       at com.synerise.sdk.core.Synerise.b(Synerise.java:5)
       at com.synerise.sdk.core.Synerise.a(Synerise.java:1)
       at com.synerise.sdk.core.Synerise$Builder.build(Synerise.java:1)
       at x.y.z.App.initSynerise(App.kt:210)
       at x.y.z.App.onCreate(App.kt:124)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4970)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1560)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

Code in App.kt:210:

```
 Synerise.Builder.with(this, getSyneriseKey(), BuildConfig.APPLICATION_ID)
            .pushRegistrationRequired(this)
            .syneriseDebugMode(BuildConfig.DEBUG)
            .crashHandlingEnabled(!BuildConfig.DEBUG)
            .build()
```

**Comment by tajchert** [comment]
```
Caused by java.lang.IllegalStateException: could not generate key in keystore
       at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
       at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
       at com.synerise.sdk.core.c.c.e.f(PreMKeySecurityManager.java:16)
       at com.synerise.sdk.core.c.c.e.c(PreMKeySecurityManager.java:1)
       at com.synerise.sdk.core.c.c.i.j(StartupManager.java:2)
       at com.synerise.sdk.core.c.c.i.b(StartupManager.java:4)
       at com.synerise.sdk.core.c.c.i.a(StartupManager.java:1)
       at com.synerise.sdk.core.Synerise.b(Synerise.java:3)
       at com.synerise.sdk.core.Synerise.a(Synerise.java:1)
       at com.synerise.sdk.core.Synerise$Builder.build(Synerise.java:1)
       at x.y.z.App.initSynerise(App.kt:204)
       at x.y.z.App.onCreate(App.kt:122)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5932)
       at android.app.ActivityThread.access$1700(ActivityThread.java:198)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
