### ISSUE TITLE
PreMKeySecurityManager.java line 16 - could not generate key in keystore

### ISSUE THREAD

**Issue by tajchert** [Synerise/android-sdk#7]
Synerise SDK version: 4.0.1

100% Samsung devices
100% Android 5 devices
60 crashes on 2 devices (one rooted one not)

Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to create application x.y.z.App: java.lang.IllegalStateException: could not generate key in keystore
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5935)
       at android.app.ActivityThread.access$1700(ActivityThread.java:198)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.IllegalStateException: could not generate key in keystore
       at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
       at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
       at com.synerise.sdk.core.c.c.e.f(PreMKeySecurityManager.java:16)
       at com.synerise.sdk.core.c.c.e.c(PreMKeySecurityManager.java:1)
       at com.synerise.sdk.core.c.c.i.j(StartupManager.java:2)
       at com.synerise.sdk.core.c.c.i.b(StartupManager.java:4)
       at com.synerise.sdk.core.c.c.i.a(StartupManager.java:1)
       at com.synerise.sdk.core.Synerise.b(Synerise.java:3)
       at com.synerise.sdk.core.Synerise.a(Synerise.java:1)
       at com.synerise.sdk.core.Synerise$Builder.build(Synerise.java:1)
       at x.y.z.App.initSynerise(App.kt:204)
       at x.y.z.App.onCreate(App.kt:122)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5932)
       at android.app.ActivityThread.access$1700(ActivityThread.java:198)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by konned** [comment]
Hi, this issue is connected with your previous opened issue: https://github.com/Synerise/android-sdk/issues/6 .
It's pre Marshmallow hardware issue. I will investigate it in next sprint.
