### ISSUE TITLE
Crash on initialization java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1

### ISSUE THREAD

**Issue by carloschance** [Synerise/android-sdk#9]
Synerise SDK version: 4.7.0, 4.8.0

Tested on:
Google Pixel 4a, 
Android 13 (33)

Invoking:
```
       
            Synerise.Builder.with(application, "xxx", getString(R.string.app_names))
                .pushRegistrationRequired(this)
                .syneriseDebugMode(BuildConfig.DEBUG)
                .crashHandlingEnabled(true)
                .build()

```
Stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 23144
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at java.util.Vector.elementData(Vector.java:734)
        at java.util.Vector.set(Vector.java:768)
        at com.synerise.sdk.event.c$b.onActivitySaveInstanceState(AutoTrackerActivityFollower.java:2)
        at android.app.Application.dispatchActivitySaveInstanceState(Application.java:524)
        at android.app.Activity.dispatchActivitySaveInstanceState(Activity.java:1533)
        at android.app.Activity.onSaveInstanceState(Activity.java:2295)
        at androidx.core.app.ComponentActivity.onSaveInstanceState(ComponentActivity.java:93)
        at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:164)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:510)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)
        at android.app.Activity.performSaveInstanceState(Activity.java:2212)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1563)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5810)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5208)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5174)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5239)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by konned** [comment]
Issue fixed in 4.7.1 and 4.8.1 versions.
